
/*if you want 
/*DROP database estore;*/
CREATE database estore;
USE estore;
CREATE TABLE customer (
	cid INT UNIQUE AUTO_INCREMENT NOT NULL,
    name VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(12) NOT NULL,
    password VARCHAR(60) NOT NULL,
    address VARCHAR(300),
    CONSTRAINT CUSTOMERPK PRIMARY KEY (cid)
);
CREATE TABLE  item(
	item_id INT UNIQUE NOT NULL AUTO_INCREMENT,
    item_name VARCHAR(45) NOT NULL,
	price DECIMAL(8,2) NOT NULL,
    qty INT NOT NULL,
    type VARCHAR(20) NOT NULL,
    photo_url VARCHAR(100),
    CONSTRAINT ITEMPK PRIMARY KEY (item_id)
);
CREATE TABLE payment(
	pid INT UNIQUE NOT NULL AUTO_INCREMENT,
    method VARCHAR(10) NOT NULL,
    amount DECIMAL(8,2)  NOT NULL,
    cid INT NOT NULL,
    CONSTRAINT PAYMENTPK PRIMARY KEY (pid),
    CONSTRAINT PAYMENTFK FOREIGN KEY (cid) REFERENCES customer(cid)
);
CREATE TABLE buy(
	pid INT NOT NULL,
    item_id INT NOT NULL,
    qty INT NOT NULL,
    CONSTRAINT BUYPK PRIMARY KEY (pid,item_id),
    CONSTRAINT BUYFK1 FOREIGN KEY (item_id)  REFERENCES item(item_id),
    CONSTRAINT BUYFK2 FOREIGN KEY (pid) REFERENCES payment(pid)
);
CREATE TABLE cart(
	cid INT NOT NULL,
    item_id INT NOT NULL,
    qty INT NOT NULL DEFAULT 0,
    CONSTRAINT CARTPK PRIMARY KEY (cid,item_id),
    CONSTRAINT CARTFK1 FOREIGN KEY (cid) REFERENCES customer(cid),
    CONSTRAINT CARTFK2 FOREIGN KEY (item_id) REFERENCES item(item_id)
);
CREATE TABLE feedback(
	fid INT NOT NULL AUTO_INCREMENT,
    cid INT NOT NULL,
    message VARCHAR(500) NOT NULL,
    CONSTRAINT FEEDBACKPK PRIMARY KEY (fid),
    CONSTRAINT FEEDBACKFK FOREIGN KEY(cid) REFERENCES customer(cid)
);
CREATE TABLE admin(
	aid INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    password VARCHAR(50) NOT NULL,
    CONSTRAINT ADMINPK PRIMARY KEY (aid)
);


